name: setup chrome

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Run Chrome
        run: google-chrome-stable --version
