name: User Input Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter a value (or press Enter for default)'
        required: false
        default: 'hello'  # Set your default value here

jobs:
  user_input_job:
    runs-on: ubuntu-latest

    steps:
    - name: Display input value
      run: |
        echo "${{ github.event.inputs.user_input}}"
