name: main
on: 

  workflow_dispatch:
    inputs:
      conf:
        description: "check the '✓' to deploy"
        required: true
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/test.yml
    if: ${{ github.event.inputs.conf == 'true' }}
