name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "192.46.210.61"
        username: "root"
        password: "Riktech@1725"
        port: "22"
        script: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-ssh-key
          # change to app directory 
          cd /root/sniffynose_api 
          # Check if any containers are running
          if [[ $(docker ps -q) ]]; then
            # If containers are running, stop Docker Compose setup
            docker-compose down
          fi
          # Assuming you have code checked out from a repository branch main , update it
          git pull origin master
          
          # Start Docker Compose setup with updated code
          docker-compose up --build -d
