name: Remote SSH Command

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "192.46.210.61"
          username: "root"
          password: "Riktech@1725"
          port: "22"
          script: |
            cd /root/sniffynose_api
            docker-compose down 
            docker-compose up --build -d \
              -e APP_ENV=${{ secrets.APP_ENV }} \
              -e ALLOWED_HOST=${{ secrets.ALLOWED_HOST }}
