name: test
on: 
  workflow_dispatch:
    inputs:
      conf:
        description: "check the '✓' to deploy"
        required: true
        type: boolean
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.conf == 'true' }}
    steps:
      - run: echo "hello"
    
